[SCANNER_CONFIG]
ENABLE = no
LINE_NO = 14
PORT_SCANNER = COM3
BAUD_RATE = 9600
API_URL = https://api.pms.yuasa.seavihive.com/api/fix-scanner

[DOWNTIME_CONFIG]
ENABLE = no
LINE_NO = 2
API_URL = https://api.pms.yuasa.seavihive.com/api/fix-scanner-downtime
DOWNTIME_LOG_FILENAME = downtime_log.txt
SAVE_LOCATION = desktop
; Pilihan CONNECTION_MODE: cx_programmer, serial, ethernet
CONNECTION_MODE = cx_programmer
PLC_IP = 192.168.1.10
PLC_PORT = COM5
PLC_BAUD = 9600
; Jika CONNECTION_MODE bukan cx_programmer, daftarkan alamat bit mesin yang dipantau (Format: SymbolName:Address:Comment)
DOWNTIME_ADDRESSES = MC1:10.01:Mesin 1, MC2:10.02:Mesin 2, MC3:10.03:Mesin 3, MC4:10.04:Mesin 4, MC5:10.05:Mesin 5, MC6:10.06:Mesin 6

[PRINTER_CONFIG]
ENABLE = yes
; Pilihan CONNECTION_MODE: cx_programmer, rockwell
CONNECTION_MODE = cx_programmer
PLC_IP = 192.168.1.20/1
PRINTER_NAME = TSC TL241
API_URL = https://api.pms.yuasa.seavihive.com/api/fix-scanner-pallet
RETRY_API_URL = https://api.pms.yuasa.seavihive.com/api/fix-scanner-pallet-retry
MONITOR_ADDRESS = 0.05
API_LINE_NO = 14
LABEL_LINE_NO = 01
LABEL_WIDTH = 70
LABEL_HEIGHT = 50
LABEL_GAP = 2
LABEL_ORIENTATION = portrait

[TIMBANGAN_CONFIG]
ENABLE = no
LINE_NO = 14
API_URL = https://api.pms.yuasa.seavihive.com/api/fix-scanner-masterbox
RETRY_API_URL = https://api.pms.yuasa.seavihive.com/api/fix-scanner-masterbox-retry
LABEL_WIDTH = 70
LABEL_HEIGHT = 50
LABEL_GAP = 2
LABEL_ORIENTATION = portrait
; Pilihan CONNECTION_MODE: rockwell, ethernet, serial, cx_programmer
CONNECTION_MODE = rockwell
PLC_IP = 192.168.1.20/1
PLC_PORT = COM6
PLC_BAUD = 9600
; Jika pakai Omron (ethernet/serial/cx_programmer), sesuaikan alamat memori (e.g. D100, D102, D110, D120)
TAG_WEIGHT = Recent_Weight
TAG_QTY = Recent_Qty
TAG_TYPE = Product_Type
TAG_TOTALIZER = Totalizer_Box
